services:
  db:
    image: postgres
    hostname: db
    restart: always
    environment:
      POSTGRES_USER: AiChecker
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: AiCheckerDB
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: AiChecker@hl-dev.de
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 8080:80

volumes:
  db:
