services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: david
      POSTGRES_PASSWORD: 123
      #POSTGRES_DB: MyDB
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: hoell@hl-dev.de
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - 8080:80
