// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using de.devcodemonkey.AIChecker.DataStore.SQLServerEF;

#nullable disable

namespace de.devcodemonkey.AIChecker.DataStore.PostgreSqlEF.Migrations
{
    [DbContext(typeof(AicheckerContext))]
    [Migration("20241024100747_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Answer", b =>
                {
                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnswerId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_Unique_AnswerId")
                        .IsUnique();

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Img", b =>
                {
                    b.Property<Guid>("ImagesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Img1")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("Img");

                    b.HasKey("ImagesId");

                    b.HasIndex("AnswerId");

                    b.ToTable("Img", (string)null);
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Model", b =>
                {
                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<string>("BaseModels")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .HasColumnType("text");

                    b.Property<double?>("Size")
                        .HasColumnType("double precision");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("ModelId");

                    b.HasIndex(new[] { "Value" }, "IX_Unique_ModelValue")
                        .IsUnique();

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            ModelId = new Guid("bafce308-ebbf-4c8a-b056-ee0c25ba5088"),
                            Description = "GPT-4o ist ein Modell, das von OpenAI entwickelt wurde. Es ist ein Sprachmodell, das auf der GPT-4-Architektur basiert.\r\nMit Stand 22.10.2024 handelt es sich mit bei dieser Version, um die aktuellste Version der GPT-4o Familie, die am 18.07.2024 veröffentlich wurde",
                            Link = "https://platform.openai.com/docs/models/gpt-4o-mini",
                            Value = "gpt-4o-mini-2024-07-18"
                        },
                        new
                        {
                            ModelId = new Guid("298ac212-d13e-49e4-92a9-d5c87e9a9013"),
                            Description = "GPT-4o ist ein Modell, das von OpenAI entwickelt wurde. Es ist ein Sprachmodell, das auf der GPT-4-Architektur basiert.\r\nMit Stand 22.10.2024 handelt es sich mit bei dieser Version, um die aktuellste Version der GPT-4o Familie, die am 06.08.2024 veröffentlich wurde",
                            Link = "https://platform.openai.com/docs/models/gpt-4o",
                            Value = "gpt-4o-2024-08-06"
                        },
                        new
                        {
                            ModelId = new Guid("d77205c2-5aec-4a31-bf45-49ed4ae25325"),
                            Value = "lmstudio -community/Phi-3.5-mini-instruct-GGUF/Phi-3.5-mini-instruct-Q4_K_M.gguf"
                        },
                        new
                        {
                            ModelId = new Guid("0e6d1bf1-838f-4b26-9ef2-90f3bdb97182"),
                            Value = "TheBloke/SauerkrautLM-7B-HerO-GGUF/sauerkrautlm-7b-hero.Q4_K_M.gguf"
                        },
                        new
                        {
                            ModelId = new Guid("aee9741a-0384-4670-ba16-56aabc3e985c"),
                            Value = "Qwen/Qwen2-0.5B-Instruct-GGUF/qwen2-0_5b-instruct-q4_0.gguf"
                        },
                        new
                        {
                            ModelId = new Guid("b518a96d-aff7-42bf-8af8-4fab75afe0bf"),
                            Value = "HuggingFaceTB/smollm-360M-instruct-v0.2-Q8_0-GGUF/smollm-360m-instruct-add-basics-q8_0.gguf"
                        },
                        new
                        {
                            ModelId = new Guid("4e791b09-6ae4-4c5c-bc5c-66110b26b108"),
                            Link = "https://platform.openai.com/docs/models/gpt-4o",
                            Value = "GPT-4 (Clipboard_-_16._Mai_2022_18_28.png)"
                        },
                        new
                        {
                            ModelId = new Guid("560d4510-9568-43b0-9210-975d8071ae45"),
                            Link = "https://platform.openai.com/docs/models/gpt-4o",
                            Value = "GPT-4 (MSTeamsReset_PD.png)"
                        },
                        new
                        {
                            ModelId = new Guid("1ae1db7b-0e46-4eef-b9d6-a9b0a140ab94"),
                            Link = "https://platform.openai.com/docs/models/gpt-4o",
                            Value = "GPT-4 (csm_teams-besprechung-fremde-kalender_a4f18f9c04.jpg)"
                        },
                        new
                        {
                            ModelId = new Guid("10cec07d-9823-4eb2-a002-f1e16abb538f"),
                            Link = "https://platform.openai.com/docs/models/gpt-4o",
                            Value = "GPT-4 (csm_exchange_ressourcen_small_8c82c9fb36.jpg)"
                        });
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.PromptRatingRound", b =>
                {
                    b.Property<Guid>("PromptRatingRoundId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<int>("Round")
                        .HasColumnType("integer");

                    b.HasKey("PromptRatingRoundId");

                    b.HasIndex("ResultId")
                        .IsUnique();

                    b.ToTable("PromptRatingRounds");

                    b.HasData(
                        new
                        {
                            PromptRatingRoundId = new Guid("e1507d31-cb0f-4449-9666-2a14862727c6"),
                            Rating = 8,
                            ResultId = new Guid("2e1cac63-bef9-4e09-8696-57e6b24545df"),
                            Round = 1
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("7a8cc490-b95a-4b6f-9f2d-ffdb3c5e72d5"),
                            Rating = 7,
                            ResultId = new Guid("5ceb114a-4cdb-46a1-9013-eb6e7db3137b"),
                            Round = 1
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("f8aff731-472e-4d6d-becc-b803cd691731"),
                            Rating = 9,
                            ResultId = new Guid("71343451-466d-4fb4-a61d-9ca36e96c8cb"),
                            Round = 1
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("be1c4ad6-180d-4165-966a-3dc1a484332f"),
                            Rating = 8,
                            ResultId = new Guid("a30dd10e-d33b-49e6-97ca-7168fb59f808"),
                            Round = 1
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("39d9364d-9d89-4276-9c38-36f6f9b202fd"),
                            Rating = 9,
                            ResultId = new Guid("5e862612-aba5-4a00-ae16-05d38317e602"),
                            Round = 2
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("970d0fc1-58c7-4c16-9890-3130560fb048"),
                            Rating = 9,
                            ResultId = new Guid("54f1e640-36ea-4c42-90e8-1a1dca526815"),
                            Round = 2
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("9695fa7c-7287-43f6-ba2d-c1a235e83bbf"),
                            Rating = 9,
                            ResultId = new Guid("a362f73e-b951-43ff-ad34-e849b297cafb"),
                            Round = 2
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("d356064b-4bbc-4553-abe0-42a0b038ed83"),
                            Rating = 9,
                            ResultId = new Guid("79ac5bb5-fbfe-46ed-9d05-5e066805020a"),
                            Round = 2
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("f9e8c322-a5fa-48e4-a0ef-a009d4d7efb3"),
                            Rating = 7,
                            ResultId = new Guid("8ae7673b-e33b-46a9-8a6f-a2d95e8e6cec"),
                            Round = 3
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("99491a5e-3441-4e89-8a60-3ec5f9406a0d"),
                            Rating = 10,
                            ResultId = new Guid("3990dcbd-6fe2-44ce-99ef-bc7db16541b5"),
                            Round = 3
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("6fba120c-2348-4c3c-8364-28015762d360"),
                            Rating = 7,
                            ResultId = new Guid("752560ff-c847-48cb-951f-aa211991c5ae"),
                            Round = 3
                        },
                        new
                        {
                            PromptRatingRoundId = new Guid("8f347e1e-8e78-41e8-88cd-282b0ac2b46b"),
                            Rating = 10,
                            ResultId = new Guid("ad36d55e-d466-4c2e-9f9e-45109b5597d3"),
                            Round = 3
                        });
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("QuestionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.RequestObject", b =>
                {
                    b.Property<Guid>("RequestObjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestObjectId");

                    b.ToTable("RequestObjects");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.RequestReason", b =>
                {
                    b.Property<Guid>("RequestReasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RequestReasonId");

                    b.ToTable("RequestReasons");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Result", b =>
                {
                    b.Property<Guid>("ResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Asked")
                        .HasColumnType("text");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RequestCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RequestEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestId")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestObjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RequestReasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RequestStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResultSetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SystemPromptId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.HasKey("ResultId");

                    b.HasIndex("ModelId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RequestObjectId");

                    b.HasIndex("RequestReasonId");

                    b.HasIndex("ResultSetId");

                    b.HasIndex("SystemPromptId");

                    b.HasIndex(new[] { "ResultId" }, "IX_Unique_ResultSetId");

                    b.ToTable("Results");

                    b.HasData(
                        new
                        {
                            ResultId = new Guid("2e1cac63-bef9-4e09-8696-57e6b24545df"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Das Bild zeigt ein Dialogfenster mit einer Fehlermeldung unter Windows. Hier sind die Details:\r\n\r\n- **Titel des Fensters**: Profilpeicherplatz\r\n- **Symbol**: Ein rotes Kreis-Symbol mit einem weißen Kreuz auf der linken Seite, das auf einen Fehler hinweist.\r\n- **Text der Fehlermeldung**: \r\n  - \"Der Profilpeicherplatz ist ausgelastet. Bevor Sie sich abmelden können, müssen Sie einige Profilelemente in das Netzwerk oder auf den lokalen Computer verschieben.\"\r\n- **Schaltflächen**: Eine Schaltfläche mit der Beschriftung \"OK\" unten rechts.\r\n\r\nDie Fehlermeldung deutet darauf hin, dass der Speicherplatz für das Benutzerprofil voll ist und Daten verschoben werden müssen, bevor eine Abmeldung möglich ist.",
                            ModelId = new Guid("4e791b09-6ae4-4c5c-bc5c-66110b26b108"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("ba86a58a-6a8b-4da2-95e9-48fe0f0c3901")
                        },
                        new
                        {
                            ResultId = new Guid("5ceb114a-4cdb-46a1-9013-eb6e7db3137b"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Das Bild zeigt einen Ausschnitt des Startmenüs eines Windows-Betriebssystems mit einer Liste installierter Programme. Im Detail:\r\n\r\n- **Hintergrundfarbe**: Dunkelgrau\r\n- **Programmliste**:\r\n  1. Microsoft Outlook\r\n  2. Microsoft Outlook Postfach Reparatur\r\n  3. Microsoft PowerPoint\r\n  4. Microsoft Teams\r\n  5. **Microsoft Teams Reset** (hervorgehoben mit einem gelben Rahmen)\r\n  6. Microsoft Word\r\n  7. Mozilla Firefox\r\n  8. Notepad++\r\n\r\n- **Hervorgehobenes Element**: \r\n  - \"Microsoft Teams Reset\" ist mit einem gelben Rahmen markiert. Dies könnte eine spezielle Funktion oder ein Skript zum Zurücksetzen von Microsoft Teams darstellen.\r\n  \r\nAuf der linken Seite des Menüs befinden sich weitere Symbole für Benutzer, Datei-Explorer, Einstellungen und E-Mail.",
                            ModelId = new Guid("560d4510-9568-43b0-9210-975d8071ae45"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("ba86a58a-6a8b-4da2-95e9-48fe0f0c3901")
                        },
                        new
                        {
                            ResultId = new Guid("71343451-466d-4fb4-a61d-9ca36e96c8cb"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Das Bild zeigt ein Dialogfenster mit einer Fehlermeldung von **Microsoft Teams**. Hier sind die Details:\r\n\r\n- **Titel des Fensters**: Microsoft Teams\r\n- **Text der Fehlermeldung**: \r\n  - \"Fehler beim Planen der Besprechung. Bitte versuchen Sie es später erneut.\"\r\n- **Schaltflächen**: Eine Schaltfläche mit der Beschriftung \"OK\" unten rechts.\r\n\r\nDie Meldung deutet darauf hin, dass ein Problem beim Erstellen oder Planen einer Besprechung in Microsoft Teams aufgetreten ist und der Nutzer gebeten wird, es später erneut zu versuchen.",
                            ModelId = new Guid("1ae1db7b-0e46-4eef-b9d6-a9b0a140ab94"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("ba86a58a-6a8b-4da2-95e9-48fe0f0c3901")
                        },
                        new
                        {
                            ResultId = new Guid("a30dd10e-d33b-49e6-97ca-7168fb59f808"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Das Bild zeigt eine kurze Erklärung zur Unterscheidung von verschiedenen Symbolen (Icons) für bestimmte Typen, wahrscheinlich in einer IT-Anwendung oder einem E-Mail-Client. Hier sind die Details:\r\n\r\n- **Text**: \r\n  - \"Durch die Icons wird die Unterscheidung zwischen den verschiedenen Typen verdeutlicht\"\r\n  - **Shared Mailbox**: Ein Symbol eines Nutzers (Kopf und Schultern) über einem Briefumschlag.\r\n  - **Raum**: Ein Symbol eines Kalenders oder eines Raumes.\r\n  - **Ausrüstung**: Ein Symbol eines Bildschirms oder Projektors.\r\n\r\nDiese Symbole sollen vermutlich dabei helfen, verschiedene Objekte wie gemeinsam genutzte Postfächer, Räume oder Ausrüstungen visuell voneinander zu unterscheiden.",
                            ModelId = new Guid("10cec07d-9823-4eb2-a002-f1e16abb538f"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("ba86a58a-6a8b-4da2-95e9-48fe0f0c3901")
                        },
                        new
                        {
                            ResultId = new Guid("5e862612-aba5-4a00-ae16-05d38317e602"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "1. Anwendung: Windows-Betriebssystem (Hinweis auf ein typisches Windows-Fehlermeldungsfenster)\r\n2. Fensterüberschrift: **\"Profilspeicherplatz\"**\r\n3. Fehlermeldung: \r\n   - **Text:** \"Der Profilspeicherplatz ist ausgelastet. Bevor Sie sich abmelden können, müssen Sie einige Profilelemente in das Netzwerk oder auf den lokalen Computer verschieben.\"\r\n4. Schaltflächen:\r\n   - **OK** (rechts unten)\r\n5. Symbol: Rotes Kreis-Symbol mit weißem Kreuz auf der linken Seite, typisches Fehler-/Warnsymbol in Windows.",
                            ModelId = new Guid("4e791b09-6ae4-4c5c-bc5c-66110b26b108"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("169eec0f-0acd-464a-af7c-1703f56f5dd6")
                        },
                        new
                        {
                            ResultId = new Guid("54f1e640-36ea-4c42-90e8-1a1dca526815"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "1. Anwendung: Startmenü von Windows\r\n        2. Geöffnete Programme im Startmenü:\r\n           - **Microsoft Outlook**\r\n           - **Microsoft Outlook Postfach Reparatur**\r\n           - **Microsoft PowerPoint**\r\n           - **Microsoft Teams**\r\n           - **Microsoft Teams Reset** (markiert mit einem gelben Rahmen)\r\n           - **Microsoft Word**\r\n           - **Mozilla Firefox**\r\n           - **Notepad++**\r\n\r\n        3. Markiertes Element: **Microsoft Teams Reset** (mit einem Symbol einer Datei und einem Zahnrad)",
                            ModelId = new Guid("560d4510-9568-43b0-9210-975d8071ae45"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("169eec0f-0acd-464a-af7c-1703f56f5dd6")
                        },
                        new
                        {
                            ResultId = new Guid("a362f73e-b951-43ff-ad34-e849b297cafb"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "1. Anwendung: Microsoft Teams\r\n        2. Fensterüberschrift: **\"Microsoft Teams\"**\r\n        3. Fehlermeldung: \r\n           - **Text:** \"Fehler beim Planen der Besprechung. Bitte versuchen Sie es später erneut.\"\r\n        4. Schaltflächen:\r\n           - **OK** (rechts unten, hervorgehoben mit blauem Rahmen)",
                            ModelId = new Guid("1ae1db7b-0e46-4eef-b9d6-a9b0a140ab94"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("169eec0f-0acd-464a-af7c-1703f56f5dd6")
                        },
                        new
                        {
                            ResultId = new Guid("79ac5bb5-fbfe-46ed-9d05-5e066805020a"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "1. Text: **\"Durch die Icons wird die Unterscheidung zwischen den verschiedenen Typen verdeutlicht\"**\r\n        2. Auflistung mit Icons:\r\n           - **Shared Mailbox:** Symbol eines orangefarbenen Kopfes mit einem Briefumschlag\r\n           - **Raum:** Symbol einer gelben Tür\r\n           - **Ausrüstung:** Symbol eines Bildschirms mit einem Ständer und einer Projektionsleinwand",
                            ModelId = new Guid("10cec07d-9823-4eb2-a002-f1e16abb538f"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("169eec0f-0acd-464a-af7c-1703f56f5dd6")
                        },
                        new
                        {
                            ResultId = new Guid("8ae7673b-e33b-46a9-8a6f-a2d95e8e6cec"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Der Eintrag enthält Bild/er:\r\n\r\n- Es handelt sich um ein Windows-Fehlermeldungsfenster.\r\n- Oben links befindet sich ein kleines Icon, das ein weißes Blatt mit einem Knick darstellt.\r\n- Titel des Fensters: „Profilspeicherplatz“.\r\n- Darunter ist ein rotes Kreis-Symbol mit einem weißen Kreuz in der Mitte.\r\n- Text im Fenster: „Der Profilspeicherplatz ist ausgelastet. Bevor Sie sich abmelden können, müssen Sie einige Profilelemente in das Netzwerk oder auf den lokalen Computer verschieben.“\r\n- Unten rechts gibt es eine Schaltfläche mit der Beschriftung „OK“.",
                            ModelId = new Guid("4e791b09-6ae4-4c5c-bc5c-66110b26b108"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("22d33939-8bbc-40cb-b355-21c7f92b4aff")
                        },
                        new
                        {
                            ResultId = new Guid("3990dcbd-6fe2-44ce-99ef-bc7db16541b5"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Der Eintrag enthält Bild/er:\r\n\r\n- Ein Ausschnitt des Startmenüs von Windows mit einer Liste installierter Programme.\r\n- Zu sehen sind unter anderem:\r\n  - Microsoft Outlook\r\n  - Microsoft Outlook Postfach Reparatur\r\n  - Microsoft PowerPoint\r\n  - Microsoft Teams\r\n  - **Markiert in einem gelben Rahmen:** „Microsoft Teams Reset“ mit einem Symbol, das eine Uhr und ein Blatt Papier zeigt.\r\n  - Microsoft Word\r\n  - Mozilla Firefox\r\n  - Notepad++\r\n- Links im Menü sind folgende Symbole sichtbar: \r\n  - Benutzerprofil\r\n  - Datei-Explorer\r\n  - Einstellungen",
                            ModelId = new Guid("560d4510-9568-43b0-9210-975d8071ae45"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("22d33939-8bbc-40cb-b355-21c7f92b4aff")
                        },
                        new
                        {
                            ResultId = new Guid("752560ff-c847-48cb-951f-aa211991c5ae"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Der Eintrag enthält Bild/er:\r\n\r\n- Es handelt sich um ein Microsoft Teams-Fehlermeldungsfenster.\r\n- Der Titel des Fensters lautet „Microsoft Teams“.\r\n- Text im Fenster: „Fehler beim Planen der Besprechung. Bitte versuchen Sie es später erneut.“\r\n- Unten rechts befindet sich eine Schaltfläche mit der Beschriftung „OK“.",
                            ModelId = new Guid("1ae1db7b-0e46-4eef-b9d6-a9b0a140ab94"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("22d33939-8bbc-40cb-b355-21c7f92b4aff")
                        },
                        new
                        {
                            ResultId = new Guid("ad36d55e-d466-4c2e-9f9e-45109b5597d3"),
                            Asked = "Es wurde nur das Bild über den GPT hochgeladen",
                            Message = "Der Eintrag enthält Bild/er:\r\n\r\n- Oben steht der Text: „Durch die Icons wird die Unterscheidung zwischen den verschiedenen Typen verdeutlicht“.\r\n- Darunter folgen drei Kategorien mit Symbolen:\r\n  - **Shared Mailbox:** Symbol einer Person mit einem orangefarbenen Kreis hinter dem Kopf.\r\n  - **Raum:** Symbol eines Kalenders oder Notizblocks mit einem Uhrensymbol.\r\n  - **Ausrüstung:** Symbol eines Bildschirms mit einem Ständer und einer Darstellung darauf.",
                            ModelId = new Guid("10cec07d-9823-4eb2-a002-f1e16abb538f"),
                            RequestCreated = new DateTime(2024, 10, 23, 22, 0, 0, 0, DateTimeKind.Utc),
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            SystemPromptId = new Guid("22d33939-8bbc-40cb-b355-21c7f92b4aff")
                        });
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.ResultSet", b =>
                {
                    b.Property<Guid>("ResultSetId")
                        .HasColumnType("uuid");

                    b.Property<string>("PromptRequierements")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ResultSetId");

                    b.HasIndex(new[] { "ResultSetId" }, "IX_Unique_ResultId");

                    b.HasIndex(new[] { "Value" }, "IX_Unique_ResultSetValue")
                        .IsUnique();

                    b.ToTable("ResultSets");

                    b.HasData(
                        new
                        {
                            ResultSetId = new Guid("51a0265a-ef30-4633-aa59-a926e7140f01"),
                            PromptRequierements = "**Erstelle eine aussagekräftige Beschreibung des hochgeladenen Bildes**\r\n- Bildinhalt sollen vom Aussehen her schriftlich dargestellt werden\r\n- Textbeschreibungen sollen, falls vorhanden, ausgelesen werden\r\n- Erkennen der Anwendung\r\n- Ausgabe als Liste\r\n- Ausgabe in deutscher Sprache",
                            Value = "Bild Beschreibungen über ChatGpt erstellen"
                        });
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.SystemPrompt", b =>
                {
                    b.Property<Guid>("SystemPromptId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SystemPromptId")
                        .HasName("PK_SystemPrompt");

                    b.ToTable("SystemPrompts");

                    b.HasData(
                        new
                        {
                            SystemPromptId = new Guid("ba86a58a-6a8b-4da2-95e9-48fe0f0c3901"),
                            Value = "Erstelle aus dem hochgeladenen Bild eine Textbeschreibung über das Aussehen. Sollte Text im Bild vorhanden sein, lesen diesen aus und fügen ihn der Beschreibung hinzu. Bei den Bildern handelt es sich um Screenshots von Anwendungen aus dem IT-Bereich. Versuche zu erkennen, um welche Anwendung es sich bei den Screenshots handelt. Gebe das Ergebnis in Form einer Liste zurück. Die Bildbeschreibung erfolgt in der deutschen Sprache."
                        },
                        new
                        {
                            SystemPromptId = new Guid("169eec0f-0acd-464a-af7c-1703f56f5dd6"),
                            Value = "Erstelle aus dem hochgeladenen Bild eine Textbeschreibung über das Aussehen. Sollte Text im Bild vorhanden sein, lesen diesen aus und fügen ihn der Beschreibung hinzu. Bei den Bildern handelt es sich um Screenshots von Anwendungen aus dem IT-Bereich. Versuche zu erkennen, um welche Anwendung es sich bei den Screenshots handelt. Gebe das Ergebnis in Form einer Liste zurück. Die Bildbeschreibung erfolgt in der deutschen Sprache. Erstelle keine Interpretation des Bildes."
                        },
                        new
                        {
                            SystemPromptId = new Guid("22d33939-8bbc-40cb-b355-21c7f92b4aff"),
                            Value = "Erstelle aus dem hochgeladenen Bild eine Textbeschreibung über das Aussehen. Sollte Text im Bild vorhanden sein, lesen diesen aus und fügen ihn der Beschreibung hinzu. Bei den Bildern handelt es sich um Screenshots von Anwendungen aus dem IT-Bereich. Versuche zu erkennen, um welche Anwendung es sich bei den Screenshots handelt. Gebe das Ergebnis in Form einer Liste zurück. Stelle an den Anfang jeder Antwort den folgenden Satz: \"Der Eintrag enthält Bild/er:\" Die Bildbeschreibung erfolgt in der deutschen Sprache. Erstelle keine Interpretation des Bildes."
                        });
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.SystemResourceUsage", b =>
                {
                    b.Property<Guid>("SystemResourceUsageId")
                        .HasColumnType("uuid");

                    b.Property<int>("CpuUsage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CpuUsageTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GpuMemoryUsage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GpuMemoryUsageTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GpuUsage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("GpuUsageTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemoryUsage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MemoryUsageTimestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ResultSetId")
                        .HasColumnType("uuid");

                    b.HasKey("SystemResourceUsageId");

                    b.HasIndex("ResultSetId");

                    b.ToTable("SystemResourceUsage", (string)null);
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Answer", b =>
                {
                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Question", "Question")
                        .WithOne("Answer")
                        .HasForeignKey("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Answer", "QuestionId")
                        .HasConstraintName("FK_Answer_Question");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Img", b =>
                {
                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Answer", "Answer")
                        .WithMany("Imgs")
                        .HasForeignKey("AnswerId")
                        .IsRequired()
                        .HasConstraintName("FK_Img_Answers");

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.PromptRatingRound", b =>
                {
                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Result", "Result")
                        .WithOne("PromptRatingRound")
                        .HasForeignKey("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.PromptRatingRound", "ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Result");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Result", b =>
                {
                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Model", "Model")
                        .WithMany("Results")
                        .HasForeignKey("ModelId")
                        .IsRequired()
                        .HasConstraintName("FK_Results_Model");

                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Question", "Question")
                        .WithMany("Results")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("FK_Results_Question");

                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.RequestObject", "RequestObject")
                        .WithMany("Results")
                        .HasForeignKey("RequestObjectId")
                        .HasConstraintName("FK_Results_RequestObjects");

                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.RequestReason", "RequestReason")
                        .WithMany("Results")
                        .HasForeignKey("RequestReasonId")
                        .HasConstraintName("FK_Results_RequestReasons");

                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.ResultSet", "ResultSet")
                        .WithMany("Results")
                        .HasForeignKey("ResultSetId")
                        .IsRequired()
                        .HasConstraintName("FK_Results_ResultSets");

                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.SystemPrompt", "SystemPrompt")
                        .WithMany("Results")
                        .HasForeignKey("SystemPromptId")
                        .HasConstraintName("FK_Results_SystemPrompts");

                    b.Navigation("Model");

                    b.Navigation("Question");

                    b.Navigation("RequestObject");

                    b.Navigation("RequestReason");

                    b.Navigation("ResultSet");

                    b.Navigation("SystemPrompt");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.SystemResourceUsage", b =>
                {
                    b.HasOne("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.ResultSet", "ResultSet")
                        .WithMany("SystemResourceUsages")
                        .HasForeignKey("ResultSetId")
                        .IsRequired()
                        .HasConstraintName("FK_SystemResourceUsage_ResultSets");

                    b.Navigation("ResultSet");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Answer", b =>
                {
                    b.Navigation("Imgs");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Model", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Question", b =>
                {
                    b.Navigation("Answer");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.RequestObject", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.RequestReason", b =>
                {
                    b.Navigation("Results");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.Result", b =>
                {
                    b.Navigation("PromptRatingRound");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.ResultSet", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("SystemResourceUsages");
                });

            modelBuilder.Entity("de.devcodemonkey.AIChecker.CoreBusiness.DbModels.SystemPrompt", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
