services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    #image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MyMS_SQLServer
    environment:
      - SA_PASSWORD=123456789!_Asdf
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql
volumes:
  sqlvolume:
    external: true #is used because the sqlvolume was created before with docker
